
’’’


 

1) Se a matrix de macadores estiver codificado como 012 (0=AA/1=AB/2=BB), o calculo de minor allele frequence seria simplesmente:

x = SNP codificada como 012

p_j = mean(x)/2

maf = min(p_j, 1-p_j )

 

2) Seguindo a mesma codificacao (012), vc pode remover SNPs colineares assim:

X = SNP matrix ( N individuals x P markers), row=P, col=N

a = random vector of length N generated by RNG

random_snp_value = X’a

SNPs que contem exatamente a mesma informacao (100% multicollinearity) vao apresentar exatamente o mesmo valor no vetor random_snp_value
’’’